.TH ktcheck "1" "June 2003" "RSUG" "User Commands"
.SH NAME
.B ktcheck 
\- verify and download command file and transcripts
.SH SYNOPSIS
.B ktcheck 
[
.BI \-c\  checksum 
.RB [ \-nrV ]
] [
.RB \-q\ |\ \-v\ |\ -i\ 
] [
.BI \-K\  command-file 
] [
.BI \-h\  host
] [
.BI \-p\  port 
] [
.BI \-w\  auth-level
] [
.BI \-x\  ca-pem-file
] [
.BI \-y\  cert-pem-file
] [ 
.BI \-z\  private-key-file
]
.sp
.SH DESCRIPTION
.B ktcheck 
verifies the command file with the radmind server 
.I host.  
The command file is downloaded from 
.I host 
if it is missing or has the wrong size.  With the -c option, checksums are
also used to verify files. 

Reading the command file line-by-line, ignoring blank lines and comments
( lines starting with # ), 
.B ktcheck 
verifies each positive and negative transcript listed, downloading it from 
.I host 
if it is missing or has a different checksum.

Each special file listed in the command file is converted into a
transcript line in special.T with information provided by 
.IR host .
See
.BR radmind (8)
for details of the STAT command.

Each special file listed in the command file is converted into a transcript line in special.T with information pro- vided by host. See radmind( for details of the STAT command.

If checksuming is turned on, the special transcript is verified using
the checksum and file size.  If either are wrong, the special transcript
is updated.
If checksuming is 
turned off, the special transcript is always updated.

Files updated by
.B ktcheck
must be regular files and the user must have access to modify them.

When run with the \-n option,
.B ktcheck
verifies but never downloads the command file or transcripts.  A tempory 
special.T is created for verification and is removed on exit.
.sp
.SH OPTIONS
.TP 19
.BI \-c\  checksum
enables checksuming.
.TP 19
.BI \-i
force output linebuffering.
.TP 19
.BI \-h\  host
specifies the radmind server, by default
.BR _RADMIND_HOST .
.TP 19
.BI \-K\  command
specifies a command file, by default
.BR _RADMIND_COMMANDFILE .
.TP 19
.B \-n
no files modified.
.TP 19
.BI \-p\  port
specifies a port, by default
.B 6662.
.TP 19
.B \-q
suppress all messages.
.TP 19
.B \-r
use random seed file $RANDFILE if that environment variable is set,
$HOME/.rnd otherwise.  See
.BR RAND_load_file (3o).
.TP 19
.B \-V
displays the version of 
.BR ktcheck ,
a list  of supported checksumming algorithms in descending
order of preference and then exits.
.TP 19
.B \-v
displays communication with the radmind server.
.TP 19
.BI \-w\  auth-level
TLS authorization level, by default _RADMIND_AUTHLEVEL.
0 = no TLS, 1 = server verification, 2 = server and client verification.
.TP 19
.BI \-x\  ca-pem-file
Certificate authority's public certificate, by default _RADMIND_TLS_CA.
.TP 19
.BI \-y\  cert-pem-file
Client's public certificate, by default _RADMIND_TLS_CERT.
.TP 19
.BI \-z\  private-key-file
Client's private key, by default _RADMIND_TLS_CERT.
.sp
.SH FILES
.TP 19
.B _RADMIND_COMMANDFILE
name of the default command file.
.TP 19
.B special.T 
name of the special transcript.
.sp
.SH EXIT STATUS
The following exit values are returned:
.TP 5
0
No differences were found. 
.TP 5
1
Differences were found.
.TP 5
>1
An error occurred.
.sp
.SH SEE ALSO
.BR fsdiff (1),
.BR lapply (1),
.BR lcksum (1),
.BR lcreate (1),
.BR lfdiff (1),
.BR lmerge (1),
.BR twhich (1),
.BR radmind (8),
.BR RAND_load_file (3o).
