.TH lapply "1" "_RADMIND_BUILD_DATE" "RSUG" "User Commands"
.SH NAME
.B lapply 
\- modify file system to match appliable-transcript 
.SH SYNOPSIS
.B lapply
.RB [ \-%FnrV ]
[
.RB \-q\ |\ \-v\ |\ \-i 
] [
.BI \-c\  checksum
] [
.BI \-h\  host
] [
.BI \-p\  port
] [
.BI \-w\  auth-level
] [
.BI \-x\  ca-pem-file
] [
.BI \-y\  cert-pem-file
] [ 
.BI \-z\  private-key-file
] {
.I appliable-transcript
}
.sp
.SH DESCRIPTION
lapply reads an appliable transcript line-by-line, modifying the file
system to match the transcript. Transcript lines are applied in order
unless they are directories marked for deletion.  In such cases,
subsequent transcript lines are first applied until the file system object 
listed is outside of the directory.  If another directory marked for
deletion is encountered, the process is started recursively.

lapply downloads missing files indicated by a "+" from the radmind server
.I host.
.I file
is applied to the system with the attributes as described in
the transcript line.  File system objects marked with a "-" are removed.
Other transcript lines indicate that a file system
object must be modified or created if missing.  lapply is not able to create doors or sockets.

File system objects listed in the transcript and present in the
file system as a different type are automatically removed.

The radmind tools are unaware of user defined file flags, some of which
may prevent lapply from successfully completing.  Using the -F option,
.B lapply
will remove all user defined flags.

If
.I appliable-transcript
is not given,
.B lapply
will use the standard input for reading.

.sp
.B lapply
is also capable of decoding
.B applefiles
stored on the server by
.B lcreate(1),
restoring the files' Mac OS HFS+ metadata to the client machine. (Mac OS X,
HFS+-formatted drives only.)
.sp
.SH OPTIONS
.TP 19
.BI \-%
percentage done progress output.
.TP 19
.BI \-c\  checksum
enables checksuming.
.TP 19
.BI \-h\  host
specifies the radmind server, by default
.BR _RADMIND_HOST .
.TP 19
.BI \-i
force output linebuffering.
.TP 19
.B \-F
remove all user defined flags for a file if they exist.
.TP 19
.B \-n
no network connection will be made, causing only file system removals and
updates to be applied.  auth-level is implicit set to 0.
.TP 19
.BI \-p\  port
specifies the port of the radmind server, by default
.BR 6662 .
.TP 19
.B \-q
suppress all messages.
.TP 19
.B \-r
use random seed file $RANDFILE if that environment variable is set,
$HOME/.rnd otherwise.  See
.BR RAND_load_file (3o).
.TP 19
.B \-V
displays the version number of
.B lapply
and exits. 
.TP 19
.B \-v
displays communication with the radmind server.
.TP 19
.BI \-w\  auth-level
TLS authorization level, by default _RADMIND_AUTHLEVEL.
0 = no TLS, 1 = server verification, 2 = server and client verification.
.TP 19
.BI \-x\  ca-pem-file
Certificate authority's public certificate, by default _RADMIND_TLS_CA.
.TP 19
.BI \-y\  cert-pem-file
Client's public certificate, by default _RADMIND_TLS_CERT.
.TP 19
.BI \-z\  private-key-file
Client's private key, by default _RADMIND_TLS_CERT.
.sp
.SH EXIT STATUS
The following exit values are returned:
.TP 5
0
Transcript was applied.
.TP 5
1
An error occurred, system was modified.
.TP 5
2
An error occurred, system was not modified.
.sp
.SH SEE ALSO
.BR fsdiff (1),
.BR ktcheck (1),
.BR lcksum (1),
.BR lcreate (1),
.BR lfdiff (1),
.BR lmerge (1),
.BR twhich (1),
.BR applefile (5),
.BR radmind (8),
.BR chflags (2),
.BR RAND_load_file (3o).
