.TH radmind "8" "August 2002" "RSUG" "System Manager's Manual"
.SH NAME
.B radmind
\- Remote administration daemon
.SH SYNOPSIS
.B radmind
[
.BI \-b\  backlog
] [
.BI \-D\  path
] [
.B \-d
] [
.BI \-L\  syslog-facility
] [
.BI \-p\  port
] [
.BI \-u\  umask 
] [
.B \-V
] [
.BI \-w\  auth-level
] [
.BI \-x\  ca-pem-file
] [
.BI \-y\  cert-pem-file
] [ 
.BI \-z\  private-key-file
]
.sp
.SH DESCRIPTION
Radmind uses the radmind access protocol to communicate with radmind
clients.
.sp
On startup, radmind changes directory to _RADMIND_PATH, creates
_RADMIND_PATH/command, _RADMIND_PATH/file,
_RADMIND_PATH/special, _RADMIND_PATH/tmp,
_RADMIND_PATH/tmp/file, _RADMIND_PATH/tmp/transcript and
_RADMIND_PATH/transcript ( with permissions 0750 ) if they do not
exist, and begins listening on the radmind port ( by default 6662 ) for
incoming connections.
With the
-D option, radmind will use
.I path
as its working directory.
Radmind forks a child for each connection.
.sp
The file _RADMIND_PATH/config contains the list of known clients that
can connect to radmind, one per line.  Each line contains the fully
qualified domain name or IP address of the client and the client's command file.
Lines that are blank or begin with '#' are ignored.
.sp
\'*' is a wildcard and will match any string.  A number range can be given 
by "<MIN-MAX>" where MIN is the lower bound and MAX is the upper bound.  '\\'
can be used to escape any character.
.sp
A client is only given access to transcripts that are listed in their config
file.
.sp
.SH DIRECTORY STRUCTURE
.TP 19
.B command
Stores the command files.
.TP 19
.B transcripts 
Stores the transcripts.
.TP 19
.B file
All files served from the radmind server are stored in the
.B file
directory.
All files for a given transcript are stored in
.B file/<TRANSCRIPT>
where <TRANSCRIPT> is the name of the transcript.  A file is stored in
.B file/<TRANSCRIPT>/<PATH>
where <PATH> is the file's path as listed in the transcript.
.TP 19
.B special
All special files are stored in
.BR special .
The special files for a given host are stored in
.B file/<HOST>
where <HOST> is the fully qualified domain name of the client.
Individual special files are stored in
.B special/<HOST>/<PATH>
where PATH is the path of the special file as listed in the client's
command file.
The IP address of the client will be used for <HOST> if there
is no domain name returned by
.BR gethostbyname() .
.TP 19
.B tmp/file
All files stored on the server using the STOR command are saved in
.BR tmp/file .
Files for a given transcript are stored in
tmp/transcript/<TRANSCRIPT>/<PATH>
where <TRANSCRIPT> is the name of the transcript and <PATH> is the file's path
as given in the STOR command.
.TP 19
.B tmp/transcript
All transcripts stored on the server using the STOR command are saved in
.BR tmp/transcript .
.sp
.SH RADMIND ACCESS PROTOCAL
Radmind currently supports the following Radmind Access Protocol ( RAP )
requests:
.sp
.TP 10
QUIT
terminate session
.TP 10
NOOP
do nothing
.TP 10
HELP
Display help message
.TP 10
STAT
stat a transcript, command or special file.  When statting a command file or
transcript, the mode, UID and GID default to 0444, 0, and 0 respectively.
Status of a special file is determined by a single transcript line listed
in a file named <SPECIAL_FILE_PATH>.T, where <SPECIAL_FILE_PATH> is the full
path to the special file.  If that does not exist, a listing for the file 
in the special.T transcript in the transcript directory will be used.
If neither of those exist, the defaults are returned.
.TP 10
RETR
retrieve a file, transcript command or special file
.TP 10
STOR
store a file or transcript
.TP 10
STAR
Start TLS.  If the server is run with an authorization level of 2, this
command must be given before a client can send a STAT, RETR, or STOR.
.sp
.SH OPTIONS
.TP 19
.BI \-b\  backlog
Defines the maximum queue of pending connections to
.BR listen (2),
by default five.
.TP 19
.BI \-D\  path
specifies the radmind working directory, by default _RADMIND_PATH
.TP 19
.B \-d
debug mode. Does not disassociate from controlling tty.
.TP 19
.B \-L\  syslog-facility
specifies which syslog-facilty to log messages to.
.TP 19
.BI \-p\  port 
specifies the port of the radmind server, by default
.BR 6662 .
.TP 19
.B \-u\  umask
specifies the umask the server uses to write files to the disk.
.TP 19
.B \-V
displays the version of 
.B  radmind
and exits.
.TP 19
.BI \-w\  auth-level
TLS authorization level, by default 0.
0 = no TLS, 1 = server verification, 2 = server and client verification.
.TP 19
.BI \-x\  ca-pem-file
Certificate authority's public certificate, by default _RADMIND_TLS_CA.
.TP 19
.BI \-y\  cert-pem-file
Server's public certificate, by default _RADMIND_TLS_CERT.
.TP 19
.BI \-z\  private-key-file
Server's private key, by default _RADMIND_TLS_CERT.
.sp
.SH EXAMPLES
The following example of _RADMIND_PATH/config defines four known clients,
each using one of three different command files.  Also, any client that ends
with ".lab.umich.edu" will get lab.K as its config file and clients
in the IP range 212.12.243.1 through 212.12.243.50 will get solaris8.K as their 
config file.
.sp
.RS
.nf
#
# Client               command file
#
amber.umich.edu        apple.K
josh.umich.ede         apple.K
ben.umich.edu          apple-test.K
oreo.umich.edu         solaris8.K
*.lab.umich.edu        lab.K
212.12.243.<1-50>      solaris8.K
.fi
.RE
.LP
.sp
.SH FILES
_RADMIND_PATH/config
.sp
.SH SEE ALSO
.BR fsdiff (1),
.BR ktcheck (1),
.BR lapply (1),
.BR lcreate (1),
.BR lcksum (1),
.BR lfdiff (1),
.BR lmerge (1),
.BR twhich (1).
