.TH radmind "8" "June 2003" "RSUG" "System Manager's Manual"
.SH NAME
.B radmind
\- Remote administration daemon
.SH SYNOPSIS
.B radmind
[
.B \-dRrUV
] [
.BI \-b\  backlog
] [
.BI \-D\  path
] [
.BI \-L\  syslog-facility
] [
.BI \-m\  max-connections 
] [
.BI \-p\  port
] [
.BI \-u\  umask 
] [
.BI \-w\  auth-level
] [
.BI \-x\  ca-pem-file
] [
.BI \-y\  cert-pem-file
] [ 
.BI \-z\  private-key-file
]
.sp
.SH DESCRIPTION
Radmind uses the radmind access protocol to communicate with radmind
clients.
.sp
On startup, radmind changes directory to _RADMIND_PATH, creates
command, file, special, tmp, tmp/file, tmp/transcript and
transcript ( with permissions 0750 ) if they do not
exist, and begins listening on the radmind port ( by default 6662 ) for
incoming connections.
With the
-D option, radmind will use
.I path
as its working directory.
Radmind forks a child for each connection.
.sp
The file config contains a list of known clients that
can connect to radmind, one per line.  Each line contains the
CN, domain name or IP address of the client and the client's
command file.  The server checks each line of the config file, first
checking to see if the connecting client's CN, doman name, and 
finally IP address match in that order.
Lines that are blank or begin with '#' are ignored.  '*' is a wildcard and
will match any string.  A number range can be given 
by "<\c
.IR min -\c
.IR max >"
where 
.I min
is the lower bound and
.I max
is the upper bound.  '\\'
can be used to escape any character. 
.sp
A client is only given access to transcripts that are listed in their config
file.
.sp
.SH DIRECTORY STRUCTURE
.TP 19
.B command
Stores command files.
.TP 19
.B transcripts 
Stores transcripts.
.TP 19
.B file
All files served from the radmind server are stored in the
.B file
directory.
All files for a given transcript are stored in
.BI file/ <transcript>
where
.I <transcript>
is the name of the transcript.  A file is stored in
.BI file/ <transcript>\c
.RI / <path>
where
.I <path>
is the file's path as listed in the transcript.
.TP 19
.B special
All special files are stored in
.BR special .
The special files for a given host are stored in
.BI special/ <host>
where
.I <host>
is the fully qualified domain name or IP address of the client.
Individual special files are stored in
.BI special/ <host>\c
.RI / <path>
where
.I <path>
is the path of the special file as listed in the client's
command file.
The IP address of the client will be used for
.I <host>
if there
is no domain name returned by
.BR gethostbyname() .
.TP 19
.B tmp/file
All files stored on the server using the STOR command are saved in
.BR tmp/file .
Files for a given transcript are stored in
.BI tmp/transcript/ <transcript>
.BI / <path>
where
.I <transcript> is the name of the transcript and
.I <path> is the file's path
as given in the STOR command.
.TP 19
.B tmp/transcript
All transcripts stored on the server using the STOR command are saved in
.BR tmp/transcript .
.sp
.SH RADMIND ACCESS PROTOCAL
Radmind currently supports the following Radmind Access Protocol ( RAP )
requests:
.sp
.TP 10
QUIT
terminate session
.TP 10
NOOP
do nothing
.TP 10
HELP
Display helpful message
.TP 10
STAT
stat a transcript, command or special file.  When statting a command file or
transcript, the mode, UID and GID default to 0444, 0, and 0 respectively.
Status of a special file is determined by a single transcript line listed
in a file named 
.BI  special/< special-file-path\c
>.T, where
.BI < special-file-path\c
> is the full
path to the special file.  If that does not exist, a listing for the file 
in the
.B transcript/special.T
transcript in the transcript directory will be used.
If neither of those exist, the defaults are returned.
.TP 10
RETR
retrieve a file, transcript command or special file
.TP 10
STOR
store a file or transcript.  If user authentication been
turned on,
this command is only valid after the client sends a successful LOGI.
.TP 10
STAR
Start TLS.  If the server is run with an authorization level of 2, this
command must be given before a client can send a STAT, RETR, or STOR.
.TP 10
LOGI
Login user.  This command is only valid after TLS has been
started. 
.sp
.SH OPTIONS
.TP 19
.BI \-b\  backlog
Defines the maximum queue of pending connections to
.BR listen (2),
by default five.
.TP 19
.BI \-D\  path
specifies the radmind working directory, by default _RADMIND_PATH
.TP 19
.B \-d
debug mode. Does not disassociate from controlling tty.
.TP 19
.BI \-L\  syslog-facility
specifies which syslog-facilty to log messages to.
.TP 19
.BI \-m\  max-connections 
specifies the maximum number of simultaneous connections, by
default _RADMIND_MAXCONNECTIONS.
Value must be greater than or equal to 0 with 0 indicating no limit.
.TP 19
.BI \-p\  port 
specifies the port of the radmind server, by default
.BR 6662 .
.TP 19
.BI \-R
registers daemon as a Rendezvous service (Mac OS X only).
.TP 19
.B \-r
use random seed file $RANDFILE if that environment variable is set,
$HOME/.rnd otherwise.  See
.BR RAND_load_file (3o).
.TP 19
.BI \-u\  umask
specifies the umask the server uses to write files to the disk, defaulting
to the user's umask.
.TP 19
.B \-U
Turn on PAM user authentication.
.B radmind
uses the PAM service name radmind.
.TP 19
.B \-V
displays the version of 
.B  radmind
and exits.
.TP 19
.BI \-w\  auth-level
TLS authorization level, by default _RADMIND_AUTHLEVEL.
0 = no TLS, 1 = server verification, 2 = server and client verification.
.TP 19
.BI \-x\  ca-pem-file
Certificate authority's public certificate, by default _RADMIND_TLS_CA.
.TP 19
.BI \-y\  cert-pem-file
Server's public certificate, by default _RADMIND_TLS_CERT.
.TP 19
.BI \-z\  private-key-file
Server's private key, by default _RADMIND_TLS_CERT.
.sp
.SH EXAMPLES
The following example of _RADMIND_PATH/config defines four known clients,
each using one of three different command files.  Also, any client that ends
with ".lab.umich.edu" will get lab.K as its config file and clients
in the IP range 212.12.243.1 through 212.12.243.50 will get solaris8.K as their 
config file.
.sp
.RS
.nf
#
# Client               command file
#
amber.umich.edu        apple.K
josh.umich.edu         apple.K
ben.umich.edu          apple-test.K
oreo.umich.edu         solaris8.K
*.lab.umich.edu        lab.K
212.12.243.<1-50>      solaris8.K
.fi
.RE
.LP
.sp
.SH FILES
_RADMIND_PATH/config
.sp
.SH SEE ALSO
.BR fsdiff (1),
.BR ktcheck (1),
.BR lapply (1),
.BR lcreate (1),
.BR lcksum (1),
.BR lfdiff (1),
.BR lmerge (1),
.BR twhich (1),
.BR pam.conf (4),
.BR RAND_load_file (3o).
.sp
Also see the three
.B Linux-PAM
Guides, for
.B System
.BR administrators ,
.B module
.BR developers ,
and
.B application
.BR developers .
