.TH ktcheck "1" "6 November 2001" "RSUG" "User Commands"
.SH NAME
.B ktcheck 
\- verify and download command file and transcripts
.SH SYNOPSIS
.B ktcheck 
.RB [ \-nvV ]
[
.BI \-c\  checksum 
] [
.BI \-K\  command-file 
] [
.BI \-h\  host
] [
.BI \-p\  port 
]
.sp
.SH DESCRIPTION
.B ktcheck 
verifies the command file with the radmind server 
.I host.  
The command file is downloaded from 
.I host 
if it is missing or has a different checksum.

Reading the command file line-by-line, ignoring blank lines and comments
( lines starting with # ), 
.B ktcheck 
verifies each positive and negative transcript listed, downloading it from 
.I host 
if it is missing or has a different checksum.

Each special file listed in the command file is converted into a
transcript line in special.T with information provided by 
.I host. 

When run with the \-n option,
.B ktcheck
verifies but never downloads the command file or transcripts.  A tempory 
special.T is created for verification and is removed on exit.
.sp
.SH OPTIONS
.TP 19
.BI \-c\  checksum
enables checksuming. sha1 is the only currently supported checksuming
algorythim.
.TP 19
.BI \-K\  command
specifies a command
file name, by default
.BR command.K .
.TP 19
.BI \-p\  port
specifies a port, by default 6662.
.TP 19
.B \-n
no files are created or downloaded.
.TP 19
.B \-v
displays verification information to the standard output.
.TP 19
.B \-V
displays the version of ktcheck and exits.
.sp
.SH FILES
.TP 19
.B command.K
name of the default command file.
.TP 19
.B special.T 
name of the special transcript.
.sp
.SH EXIT STATUS
The following exit values are returned:
.TP 5
0
No differences were found. 
.TP 5
1
Differences were found.
.TP 5
>1
An error occurred.
.sp
.SH SEE ALSO
.BR fsdiff (1),
.BR lapply (1),
.BR lcksum (1),
.BR lcreate (1),
.BR lfdiff (1),
.BR lmerge (1),
.BR radmind (8).
