#!/bin/sh

. /etc/rc.common

##
# Start up radmind server
##

if [ "${RADMINDSERVER:=-YES-}" = "-YES-" ]; then
    CheckForNetwork

    if [ "${NETWORKUP}" = "-NO-" ]; then exit; fi

    ConsoleMessage "Starting Radmind Server"

    /usr/local/sbin/radmind

fi
