d ./.Trashes                            0333     0     0
d ./.vol                                0444     0     0
d ./Library/Caches                      0755     0     0
d ./Library/ColorSync/Profiles/Displays 0777     0     0
d ./Library/Preferences                 0775     0     0
d ./Network/Servers                     0555     0     0
d ./System/Library/Caches               0755     0     0
f ./System/Library/Extensions.mkext     0644     0     0 1015476977       0 2jmj7l5rSw0yVb/vlWAYkK/YBwk=
f ./System/Library/Filesystems/hfs.fs/hfs.label 0644     0     0 1014309820   4 mVS1y2Rq8+HWL4k27oAuOZ4WTv4=
f ./System/Library/Filesystems/hfs.fs/hfs.name 0644     0     0 1014309820    3 Sa6JRLWxLcf8KQzcVEi1R9HaBp8=
d ./Users                               0755     0     0
d ./Volumes                             1777     0     0
d ./dev                                 0555     0     0
f ./mach.sym                            0444     0     0 1014310508  563812 6rG3b+tUiem3ycBySprZ7IuRy8o=
d ./private/etc/httpd/users             0755     0     0
d ./private/tmp                         1777     0     0
d ./private/var/db                      0755     0     0
d ./private/var/log                     0755     0     0
d ./private/var/radmind/client          0755     0     0
d ./private/var/root                    0750     0     0
d ./private/var/run                     0775     0     1
f ./private/var/sleep.out               0644     0     0 1015477570       0 2jmj7l5rSw0yVb/vlWAYkK/YBwk=
d ./private/var/spool/printing          0775     1     1
d ./private/var/tmp                     1777     0     0
d ./private/var/vm                      0755     0     0
