#!/bin/sh

. /etc/rc.common

##
# Start up radmind server
##

if [ -f /var/radmind/config ]; then
    CheckForNetwork

    if [ "${NETWORKUP}" = "-NO-" ]; then exit; fi

    ConsoleMessage "Starting Radmind Server"

    /usr/local/sbin/radmind

fi
