#!/bin/sh

##
# radmind server
##

. /etc/rc.common

StartService()
{
    if [ -f /var/radmind/config ]; then
	ConsoleMessage "Starting Radmind Server"

	/usr/local/sbin/radmind -u 077

    fi
}

StopService()
{
    ConsoleMessage "Stopping Radmind Server"
    killall radmind
}

RestartService()
{
    StopService
    StartService
}

RunService "$1"
