name: Build
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    strategy:
      matrix:
        os: [ macos-10.15, macos-11 ]
    name: ${{ matrix.os }} radmind
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Configure
        run: |
          if [ "$RUNNER_OS" == "macOS" ]; then
              brew install openssl
              sudo ln -s /usr/local/opt/openssl /usr/local/openssl 
          fi
          sh bootstrap.sh
          ./configure
      - name: Build
        run: |
          make package
